const translations = {
    "zh-TW": {
        // --- 通用 ---
        "web-title": "睿學社 - 官方網站",
        "logo": "睿學社",
        "nav-home": "首頁",
        "nav-download": "下載連結",
        "nav-about": "關於學會",
        "nav-news": "最新消息",
        "nav-services": "會員服務",
        "nav-contact": "聯絡我們",
        "footer-addr": "地址：在綫",
        "footer-contact": "電話：(44) 7450954610 | 信箱：Learnaholics@Learnaholicsclub.uk",
        
        // --- index.html 專用 ---
        "hero-title": "凝聚學會力量 · 引領時代未來",
        "hero-desc": "本會致力於度卡蹭。",
        "hero-btn": "申請入會",
        "about-title": "學會簡介",
        "about-desc": "本學會成立於西元 2026 年，為依法設立之非營利學會。本會以協調同業關係、增進共同利益、開拓國內外市場、並以推進學術提升為宗旨。歷年來積極配合政府政策，反映會員意見，成為政府與產業間最堅實的溝通橋樑。",
        "services-title": "服務範疇",
        "card1-title": "學術交流",
        "card1-desc": "提供學術交流環境。",
        "card2-title": "課程交互",
        "card2-desc": "教學新思想",
        "card3-title": "戀愛交友",
        "card3-desc": "致力於推進人類生育計劃",
        
        // --- about.html 專用 (新增內容) ---
        "about-hero-title": "深耕學術，引領變革",
        "about-hero-subtitle": "自 2026 年起，我們致力於成為全球知識交流的樞紐",
        "stat1": "100+", "stat1-desc": "合作機構",
        "stat2": "5000+", "stat2-desc": "活躍會員",
        "stat3": "20+", "stat3-desc": "年度活動",
        "stat4": "15", "stat4-desc": "專業委員會",
        "history-title": "發展沿革",
        "history-long-desc": "本學會自 2026 年成立以來，從最初的小型研討會，逐漸成長為具國際影響力的學術平台，持續推動產業轉型與知識創新，累積了豐富的產業合作經驗。",
        "values-title": "核心價值",
        "v1-title": "誠信為本", "v1-desc": "堅守學術倫理與誠信原則。",
        "v2-title": "跨界創新", "v2-desc": "鼓勵不同領域間的碰撞與整合。",
        "v3-title": "社會責任", "v3-desc": "將學術研究轉化為實際的社會貢獻。"
    },
    "zh-HK": {
        "web-title": "睿學社 - 官方網站",
        "logo": "睿學社",
        "nav-home": "首頁",
        "nav-download": "下載連結",
        "nav-about": "關於學會",
        "nav-news": "最新消息",
        "nav-services": "會員服務",
        "nav-contact": "聯絡我們",
        "footer-addr": "地址：在線",
        "footer-contact": "電話：(44) 7450954610 | 電郵：Learnaholics@Learnaholicsclub.uk",
        
        "hero-title": "凝聚學會力量 · 引領時代未來",
        "hero-desc": "本會致力於度卡蹭。",
        "hero-btn": "申請入會",
        "about-title": "學會簡介",
        "about-desc": "本學會成立於 2026 年，為依法設立之非牟利學會。本會以協調同業關係、增進共同利益、開拓國內外市場、並以推進學術提升為宗旨。歷年來積極配合政府政策，反映會員意見，成為政府與產業間最堅實的溝通橋樑。",
        "services-title": "服務範疇",
        "card1-title": "學術交流", "card1-desc": "提供學術交流環境。",
        "card2-title": "課程交互", "card2-desc": "教學新思想",
        "card3-title": "戀愛交友", "card3-desc": "致力於推進人類生育計劃",
        
        "about-hero-title": "深耕學術，引領變革",
        "about-hero-subtitle": "自 2026 年起，我們致力於成為全球知識交流的樞紐",
        "stat1": "100+", "stat1-desc": "合作機構",
        "stat2": "5000+", "stat2-desc": "活躍會員",
        "stat3": "20+", "stat3-desc": "年度活動",
        "stat4": "15", "stat4-desc": "專業委員會",
        "history-title": "發展沿革",
        "history-long-desc": "本學會自 2026 年成立以來，從最初的小型研討會，逐漸成長為具國際影響力的學術平台，持續推動產業轉型與知識創新，累積了豐富的產業合作經驗。",
        "values-title": "核心價值",
        "v1-title": "誠信為本", "v1-desc": "堅守學術倫理與誠信原則。",
        "v2-title": "跨界創新", "v2-desc": "鼓勵不同領域間的碰撞與整合。",
        "v3-title": "社會責任", "v3-desc": "將學術研究轉化為實際的社會貢獻。"
    },
    "zh-CN": {
        "web-title": "睿学社 - 官方网站",
        "logo": "睿学社",
        "nav-home": "首页",
        "nav-download": "下载链接",
        "nav-about": "关于学会",
        "nav-news": "最新消息",
        "nav-services": "会员服务",
        "nav-contact": "联系我们",
        "footer-addr": "地址：在线",
        "footer-contact": "电话：(44) 7450954610 | 邮箱：Learnaholics@Learnaholicsclub.uk",
        
        "hero-title": "凝聚学会力量 · 引领时代未来",
        "hero-desc": "本会致力于度卡蹭。",
        "hero-btn": "申请入会",
        "about-title": "学会简介",
        "about-desc": "本学会成立于公元 2026 年，为依法设立之非营利学会。本会以协调同业关系、增进共同利益、开拓国内外市场、并以推进学术提升为宗旨。历年来积极配合政府政策，反映会员意见，成为政府与产业间最坚实的沟通桥梁。",
        "services-title": "服务范畴",
        "card1-title": "学术交流", "card1-desc": "提供学术交流环境。",
        "card2-title": "课程交互", "card2-desc": "教学新思想",
        "card3-title": "恋爱交友", "card3-desc": "致力于推进人类生育计划",
        
        "about-hero-title": "深耕学术，引领变革",
        "about-hero-subtitle": "自 2026 年起，我们致力于成为全球知识交流的枢纽",
        "stat1": "100+", "stat1-desc": "合作机构",
        "stat2": "5000+", "stat2-desc": "活跃会员",
        "stat3": "20+", "stat3-desc": "年度活动",
        "stat4": "15", "stat4-desc": "专业委员会",
        "history-title": "发展沿革",
        "history-long-desc": "本学会自 2026 年成立以来，从最初的小型研讨会，逐渐成长为具国际影响力的学术平台，持续推动产业转型与知识创新，积累了丰富的产业合作经验。",
        "values-title": "核心价值",
        "v1-title": "诚信为本", "v1-desc": "坚守学术伦理与诚信原则。",
        "v2-title": "跨界创新", "v2-desc": "鼓励不同领域间的碰撞与整合。",
        "v3-title": "社会责任", "v3-desc": "将学术研究转化为实际的社会贡献。"
    },
    "en": {
        "web-title": "Learnaholics Club - Official Website",
        "logo": "Learnaholics Club",
        "nav-home": "Home",
        "nav-download": "Downloads",
        "nav-about": "About Us",
        "nav-news": "Latest News",
        "nav-services": "Member Services",
        "nav-contact": "Contact Us",
        "footer-addr": "Address: Online",
        "footer-contact": "Tel: (44) 7450954610 | Email: Learnaholics@Learnaholicsclub.uk",
        
        "hero-title": "Uniting Power · Leading the Future",
        "hero-desc": "Dedicated to exploration and innovation.",
        "hero-btn": "Join Us",
        "about-title": "About Us",
        "about-desc": "Founded in 2026, Learnaholics Club is a non-profit organization dedicated to fostering academic exchange, promoting shared interests, and bridging the gap between industry and government.",
        "services-title": "Our Services",
        "card1-title": "Academic Exchange", "card1-desc": "Providing a platform for scholarly collaboration.",
        "card2-title": "Curriculum Interaction", "card2-desc": "Teaching innovative ideas.",
        "card3-title": "Social Networking", "card3-desc": "Committed to supporting human development.",
        
        "about-hero-title": "Deepening Scholarship, Leading Innovation",
        "about-hero-subtitle": "Since 2026, we have been dedicated to becoming a global hub for knowledge exchange.",
        "stat1": "100+", "stat1-desc": "Partners",
        "stat2": "5000+", "stat2-desc": "Members",
        "stat3": "20+", "stat3-desc": "Events",
        "stat4": "15", "stat4-desc": "Committees",
        "history-title": "Our History",
        "history-long-desc": "Since our establishment in 2026, we have grown from a small study group into an influential international academic platform, continuously driving industrial transformation and knowledge innovation.",
        "values-title": "Core Values",
        "v1-title": "Integrity", "v1-desc": "Upholding academic ethics and integrity.",
        "v2-title": "Innovation", "v2-desc": "Encouraging interdisciplinary collaboration.",
        "v3-title": "Social Responsibility", "v3-desc": "Translating research into societal contributions."
    }
};