// 全球 32 種語言完整字串配置（含港台精確本地化，100% 無縮寫、無遺漏）
const translations = {
    // ==========================================
    // 1. 中文語系
    // ==========================================
    "zh-TW": {
        "web-title": "睿學社 - 官方網站",
        "logo": "睿學社",
        "nav-home": "首頁",
        "nav-download": "下載鏈接",
        "nav-about": "關於公會",
        "nav-news": "最新消息",
        "nav-services": "會員服務",
        "nav-contact": "聯絡我們",
        "hero-title": "凝聚學會力量 · 引領時代未來",
        "hero-desc": "本會致力於度卡蹭。",
        "hero-btn": "申請入會",
        "about-title": "學會簡介",
        "about-desc": "促進學術交流，推進知識共享，服務會員發展，一個由自願學習愛好者組成的非盈利學術交流平臺。",
        "services-title": "服務範疇",
        "card1-title": "學術交流",
        "card1-desc": "提供學術交流環境。",
        "card2-title": "課程交互",
        "card2-desc": "教學新思想",
        "card3-title": "戀愛交友",
        "card3-desc": "致力於推進人類生育計劃",
        "footer-addr": "地址：在綫",
        "footer-contact": "電話：(44) 7450954610 | 信箱：Learnaholics@Learnaholicsclub.uk"
    },
    "zh-HK": {
        "web-title": "睿學社 - 官方網站",
        "logo": "睿學社",
        "nav-home": "首頁",
        "nav-download": "下載連結",
        "nav-about": "關於公會",
        "nav-news": "最新消息",
        "nav-services": "會員服務",
        "nav-contact": "聯絡我們",
        "hero-title": "凝聚學會力量 · 引領時代未來",
        "hero-desc": "本會致力於度卡蹭。",
        "hero-btn": "申請入會",
        "about-title": "學會簡介",
        "about-desc": "促進學術交流，推進知識共享，服務會員發展，一個由自願學習愛好者組成的非牟利學術交流平台。",
        "services-title": "服務範疇",
        "card1-title": "學術交流",
        "card1-desc": "提供學術交流環境。",
        "card2-title": "課程交互",
        "card2-desc": "教學新思想",
        "card3-title": "戀愛交友",
        "card3-desc": "致力於推進人類生育計劃",
        "footer-addr": "地址：在線",
        "footer-contact": "電話：(44) 7450954610 | 電郵：Learnaholics@Learnaholicsclub.uk"
    },
    "zh-CN": {
        "web-title": "睿学社 - 官方网站",
        "logo": "睿学社",
        "nav-home": "首页",
        "nav-download": "下载链接",
        "nav-about": "关于公会",
        "nav-news": "最新消息",
        "nav-services": "会员服务",
        "nav-contact": "联系我们",
        "hero-title": "凝聚学会力量 · 引领时代未来",
        "hero-desc": "本会致力于度卡蹭。",
        "hero-btn": "申请入会",
        "about-title": "学会简介",
        "about-desc": "促进学术交流，推进知识共享，服务会员发展，一个由自愿学习爱好者组成的非盈利学术交流平台。",
        "services-title": "服务范畴",
        "card1-title": "学术交流",
        "card1-desc": "提供学术交流环境。",
        "card2-title": "课程交互",
        "card2-desc": "教学新思想",
        "card3-title": "恋爱交友",
        "card3-desc": "致力于推进人类生育计划",
        "footer-addr": "地址：在线",
        "footer-contact": "电话：(44) 7450954610 | 邮箱：Learnaholics@Learnaholicsclub.uk"
    },

    // ==========================================
    // 2. 亞太語系
    // ==========================================
    "ja": {
        "web-title": "Learnaholics Clubs - 公式サイト",
        "logo": "Learnaholics Clubs",
        "nav-home": "ホーム",
        "nav-download": "ダウンロードリンク",
        "nav-about": "学会について",
        "nav-news": "最新ニュース",
        "nav-services": "会員サービス",
        "nav-contact": "お問い合わせ",
        "hero-title": "学会の力を結集し、時代の未来をリードする",
        "hero-desc": "当学会はドゥ・カ・ツェンに尽力しています。",
        "hero-btn": "入会申請",
        "about-title": "学会紹介",
        "about-desc": "学術交流を促進し、知識の共有を推進し、会員の発展に尽くす、ボランティアの学習愛好家によって構成された非営利の学術交流プラットフォームです。",
        "services-title": "サービス分野",
        "card1-title": "学術交流",
        "card1-desc": "学術交流のための環境を提供します。",
        "card2-title": "カリキュラム交流",
        "card2-desc": "新しい教育思想の普及。",
        "card3-title": "交際・ネットワーキング",
        "card3-desc": "人類の育成計画の推進に貢献します。",
        "footer-addr": "住所：オンライン",
        "footer-contact": "電話：(44) 7450954610 | メール：Learnaholics@Learnaholicsclub.uk"
    },
    "ko": {
        "web-title": "Learnaholics Clubs - 공식 웹사이트",
        "logo": "Learnaholics Clubs",
        "nav-home": "홈",
        "nav-download": "다운로드 링크",
        "nav-about": "학회 소개",
        "nav-news": "최신 뉴스",
        "nav-services": "회원 서비스",
        "nav-contact": "문의하기",
        "hero-title": "학회의 힘을 모아 · 시대의 미래를 선도하다",
        "hero-desc": "본 학회는 두카청에 전념하고 있습니다.",
        "hero-btn": "입회 신청",
        "about-title": "학회 소개",
        "about-desc": "학술 교류 증진, 지식 공유 추진, 회원 발전 지원을 목적으로 자발적인 학습 애호가들로 구성된 비영리 학술 교류 플랫폼입니다.",
        "services-title": "서비스 범위",
        "card1-title": "학술 교류",
        "card1-desc": "학술 교류를 위한 최적의 환경을 제공합니다.",
        "card2-title": "교육 과정 상호작용",
        "card2-desc": "새로운 교육 사상 전파.",
        "card3-title": "연애 및 교류",
        "card3-desc": "인류 출산 및 발전 계획 추진에 기여합니다.",
        "footer-addr": "주소: 온라인",
        "footer-contact": "전화: (44) 7450954610 | 이메일: Learnaholics@Learnaholicsclub.uk"
    },
    "vi": {
        "web-title": "Learnaholics Clubs - Trang web chính thức",
        "logo": "Learnaholics Clubs",
        "nav-home": "Trang chủ",
        "nav-download": "Tải xuống",
        "nav-about": "Giới thiệu",
        "nav-news": "Tin tức",
        "nav-services": "Dịch vụ hội viên",
        "nav-contact": "Liên hệ",
        "hero-title": "Hội tụ sức mạnh · Dẫn dắt tương lai thời đại",
        "hero-desc": "Hội chúng tôi tận tâm vì Du-Ka-Ceng.",
        "hero-btn": "Gia nhập hội",
        "about-title": "Giới thiệu học hội",
        "about-desc": "Thúc đẩy trao đổi học thuật, đẩy mạnh chia sẻ kiến thức, phục vụ sự phát triển của hội viên, một nền tảng trao đổi học thuật phi lợi nhuận bao gồm những người đam mê học tập tự nguyện.",
        "services-title": "Lĩnh vực dịch vụ",
        "card1-title": "Trao đổi học thuật",
        "card1-desc": "Cung cấp môi trường trao đổi học thuật.",
        "card2-title": "Tương tác khóa học",
        "card2-desc": "Giảng dạy tư duy mới giáo dục.",
        "card3-title": "Hẹn hò & Giao lưu",
        "card3-desc": "Thúc đẩy kế hoạch sinh sản của nhân loại.",
        "footer-addr": "Địa chỉ: Trực tuyến",
        "footer-contact": "ĐT: (44) 7450954610 | Email: Learnaholics@Learnaholicsclub.uk"
    },
    "th": {
        "web-title": "Learnaholics Clubs - เว็บไซต์อย่างเป็นทางการ",
        "logo": "Learnaholics Clubs",
        "nav-home": "หน้าแรก",
        "nav-download": "ดาวน์โหลด",
        "nav-about": "เกี่ยวกับเรา",
        "nav-news": "ข่าวสาร",
        "nav-services": "บริการสมาชิก",
        "nav-contact": "ติดต่อเรา",
        "hero-title": "รวมพลังสมาคม · นำอนาคตแห่งยุคสมัย",
        "hero-desc": "สมาคมของเรามุ่งมั่นเพื่อ Du-Ka-Ceng",
        "hero-btn": "สมัครสมาชิก",
        "about-title": "เกี่ยวกับสมาคม",
        "about-desc": "ส่งเสริมการแลกเปลี่ยนทางวิชาการ ขับเคลื่อนการแบ่งปันความรู้ และบริการพัฒนาสมาชิก แพลตฟอร์มแลกเปลี่ยนทางวิชาการที่ไม่แสวงหาผลกำไรที่จัดตั้งขึ้นโดยกลุ่มผู้รักการเรียนรู้ด้วยความสมัครใจ",
        "services-title": "ขอบเขตบริการ",
        "card1-title": "แลกเปลี่ยนวิชาการ",
        "card1-desc": "จัดสภาพแวดล้อมเพื่อการแลกเปลี่ยนทางวิชาการ",
        "card2-title": "ปฏิสัมพันธ์หลักสูตร",
        "card2-desc": "สอนแนวคิดใหม่ๆ ทางการศึกษา",
        "card3-title": "หาเพื่อนและเดท",
        "card3-desc": "มุ่งมั่นที่จะขับเคลื่อนแผนการเจริญพันธุ์ของมนุษยชาติ",
        "footer-addr": "ที่อยู่: ออนไลน์",
        "footer-contact": "โทร: (44) 7450954610 | อีเมล: Learnaholics@Learnaholicsclub.uk"
    },
    "id": {
        "web-title": "Learnaholics Clubs - Situs Resmi",
        "logo": "Learnaholics Clubs",
        "nav-home": "Beranda",
        "nav-download": "Unduhan",
        "nav-about": "Tentang Kami",
        "nav-news": "Berita",
        "nav-services": "Layanan",
        "nav-contact": "Kontak",
        "hero-title": "Menyatukan Kekuatan · Memimpin Masa Depan",
        "hero-desc": "Masyarakat kami berdedikasi untuk Du-Ka-Ceng.",
        "hero-btn": "Bergabung",
        "about-title": "Tentang Kami",
        "about-desc": "Mempromosikan pertukaran akademik, mendorong pembagian pengetahuan, dan melayani pengembangan anggota, sebuah platform pertukaran akademik nirlaba yang terdiri dari para pencinta pembelajaran sukarela.",
        "services-title": "Layanan",
        "card1-title": "Pertukaran Akademik",
        "card1-desc": "Menyediakan lingkungan untuk pertukaran akademik.",
        "card2-title": "Kursus Interaktif",
        "card2-desc": "Mengajarkan pemikiran baru dalam pendidikan.",
        "card3-title": "Dating & Jaringan",
        "card3-desc": "Berdedikasi untuk memajukan rencana reproduksi manusia.",
        "footer-addr": "Alamat: Online",
        "footer-contact": "Telp: (44) 7450954610 | Email: Learnaholics@Learnaholicsclub.uk"
    },
    "ms": {
        "web-title": "Learnaholics Clubs - Laman Rasmi",
        "logo": "Learnaholics Clubs",
        "nav-home": "Utama",
        "nav-download": "Muat Turun",
        "nav-about": "Mengenai Kami",
        "nav-news": "Berita",
        "nav-services": "Perkhidmatan",
        "nav-contact": "Hubungi",
        "hero-title": "Menyatukan Kekuatan · Memimpin Masa Depan",
        "hero-desc": "Pertubuhan kami berdedikasi untuk Du-Ka-Ceng.",
        "hero-btn": "Sertai",
        "about-title": "Mengenai Kami",
        "about-desc": "Mempromosikan pertukaran akademik, memajukan perkongsian ilmu, and menyokong pembangunan ahli, sebuah platform pertukaran akademik bukan untung yang terdiri daripada peminat pembelajaran sukarela.",
        "services-title": "Perkhidmatan",
        "card1-title": "Pertukaran Akademik",
        "card1-desc": "Menyediakan persekitaran yang kondusif untuk pertukaran akademik.",
        "card2-title": "Interaksi Kursus",
        "card2-desc": "Mengajar pemikiran baharu dalam pendidikan.",
        "card3-title": "Janji Temu & Sosial",
        "card3-desc": "Didedikasikan untuk memajukan rancangan pembiakan manusia.",
        "footer-addr": "Alamat: Atas Talian",
        "footer-contact": "Tel: (44) 7450954610 | E-mel: Learnaholics@Learnaholicsclub.uk"
    },
    "fil": {
        "web-title": "Learnaholics Clubs - Opisyal na Website",
        "logo": "Learnaholics Clubs",
        "nav-home": "Home",
        "nav-download": "Downloads",
        "nav-about": "Tungkol sa Amin",
        "nav-news": "Balita",
        "nav-services": "Serbisyo",
        "nav-contact": "Makipag-ugnayan",
        "hero-title": "Pagkakaisa ng Lakas · Pamumuno sa Haharapin",
        "hero-desc": "Ang aming samahan ay nakatuon sa Du-Ka-Ceng.",
        "hero-btn": "Sumali",
        "about-title": "Tungkol sa Amin",
        "about-desc": "Pagtataguyod ng palitang akademiko, pagsusulong ng pagbabahagi ng kaalaman, at paglilingkod sa pag-unlad ng kasapi, isang non-profit na plataporma ng palitang akademiko na binubuo ng mga boluntaryong mahilig mag-aral.",
        "services-title": "Serbisyo",
        "card1-title": "Palitang Akademiko",
        "card1-desc": "Nagbibigay ng magandang kapaligiran para sa akademikong talakayan.",
        "card2-title": "Interaksyon sa Kurso",
        "card2-desc": "Pagtuturo ng mga bagong ideya sa edukasyon.",
        "card3-title": "Dating at Pakikipagkapwa",
        "card3-desc": "Nakatuon sa pagsusulong ng mga plano para sa populasyon ng tao.",
        "footer-addr": "Address: Online",
        "footer-contact": "Tel: (44) 7450954610 | Email: Learnaholics@Learnaholicsclub.uk"
    },
    "hi": {
        "web-title": "Learnaholics Clubs - आधिकारिक वेबसाइट",
        "logo": "Learnaholics Clubs",
        "nav-home": "होम",
        "nav-download": "डाउनलोड",
        "nav-about": "हमारे बारे में",
        "nav-news": "समाचार",
        "nav-services": "सेवाएं",
        "nav-contact": "संपर्क करें",
        "hero-title": "शक्ति एकजुट · भविष्य का नेतृत्व",
        "hero-desc": "हमारी संस्था Du-Ka-Ceng के लिए समर्पित है।",
        "hero-btn": "शामिल हों",
        "about-title": "परिचय",
        "about-desc": "शैक्षणिक आदान-प्रदान को बढ़ावा देना, ज्ञान साझा करना और सदस्यों के विकास की सेवा करना, स्वैच्छिक शिक्षण प्रेमियों से बना एक गैर-लाभकारी शैक्षणिक आदान-प्रदान मंच।",
        "services-title": "सेवाएं",
        "card1-title": "शैक्षणिक आदान-प्रदान",
        "card1-desc": "अकादमिक आदान-प्रदान के लिए एक सक्षम वातावरण प्रदान करना।",
        "card2-title": "पाठ्यक्रम सहभागिता",
        "card2-desc": "शिक्षा के क्षेत्र में नए विचारों का प्रसार करना।",
        "card3-title": "नेटवर्किंग और संबंध",
        "card3-desc": "मानव विकास और पारिवारिक योजनाओं को बढ़ावा देने के लिए समर्पित।",
        "footer-addr": "पता: ऑनलाइन",
        "footer-contact": "फोन: (44) 7450954610 | ईमेल: Learnaholics@Learnaholicsclub.uk"
    },

    // ==========================================
    // 3. 歐美主流語系
    // ==========================================
    "en": {
        "web-title": "Learnaholics Clubs - Official Website",
        "logo": "Learnaholics Clubs",
        "nav-home": "Home",
        "nav-download": "Downloads",
        "nav-about": "About Us",
        "nav-news": "News",
        "nav-services": "Services",
        "nav-contact": "Contact",
        "hero-title": "Uniting Our Strength · Leading the Future",
        "hero-desc": "We are dedicated to Du-Ka-Ceng.",
        "hero-btn": "Join Us",
        "about-title": "About Us",
        "about-desc": "Promoting academic exchange, sharing knowledge, and serving member development, a non-profit academic platform composed of voluntary learners.",
        "services-title": "Services",
        "card1-title": "Academic Exchange",
        "card1-desc": "Providing an academic environment.",
        "card2-title": "Course Interaction",
        "card2-desc": "Teaching new ideas.",
        "card3-title": "Dating & Networking",
        "card3-desc": "Dedicated to advancing human reproduction plans.",
        "footer-addr": "Address: Online",
        "footer-contact": "Tel: (44) 7450954610 | Email: Learnaholics@Learnaholicsclub.uk"
    },
    "es": {
        "web-title": "Learnaholics Clubs - Sitio Oficial",
        "logo": "Learnaholics Clubs",
        "nav-home": "Inicio",
        "nav-download": "Descargas",
        "nav-about": "Sobre Nosotros",
        "nav-news": "Noticias",
        "nav-services": "Servicios",
        "nav-contact": "Contacto",
        "hero-title": "Uniendo Fuerzas · Liderando el Futuro de la Era",
        "hero-desc": "Nuestra sociedad está dedicada a Du-Ka-Ceng.",
        "hero-btn": "Registrarse",
        "about-title": "Acerca de la Sociedad",
        "about-desc": "Promover el intercambio académico, impulsar el conocimiento compartido y servir al desarrollo de los miembros, una plataforma de intercambio académico sin fines de lucro compuesta por estudiantes voluntarios.",
        "services-title": "Ámbito de Servicios",
        "card1-title": "Intercambio Académico",
        "card1-desc": "Proporcionar un entorno favorable para el intercambio académico.",
        "card2-title": "Interacción de Cursos",
        "card2-desc": "Enseñando nuevas ideas educativas progresistas.",
        "card3-title": "Citas y Contactos",
        "card3-desc": "Dedicado a avanzar en los planes de reproducción y desarrollo humano.",
        "footer-addr": "Dirección: En Línea",
        "footer-contact": "Tel: (44) 7450954610 | Correo: Learnaholics@Learnaholicsclub.uk"
    },
    "fr": {
        "web-title": "Learnaholics Clubs - Site Officiel",
        "logo": "Learnaholics Clubs",
        "nav-home": "Accueil",
        "nav-download": "Téléchargements",
        "nav-about": "À Propos",
        "nav-news": "Actualités",
        "nav-services": "Services",
        "nav-contact": "Contact",
        "hero-title": "Unir les Forces · Guider l'Avenir de l'Ère",
        "hero-desc": "Notre société est dédiée à Du-Ka-Ceng.",
        "hero-btn": "Devenir Membre",
        "about-title": "Présentation",
        "about-desc": "Promouvoir les échanges académiques, faire progresser le partage des connaissances et soutenir le développement des membres, une plateforme d'échange académique à but non lucratif composée d'apprenants volontaires.",
        "services-title": "Domaines de Services",
        "card1-title": "Échanges Académiques",
        "card1-desc": "Offrir un environnement propice aux échanges académiques.",
        "card2-title": "Interaction des Cours",
        "card2-desc": "Enseigner de nouvelles pensées éducatives progressistes.",
        "card3-title": "Rencontres & Réseautage",
        "card3-desc": "Dédié à l'avancement des plans de reproduction humaine.",
        "footer-addr": "Adresse: En Ligne",
        "footer-contact": "Tél: (44) 7450954610 | Email: Learnaholics@Learnaholicsclub.uk"
    },
    "de": {
        "web-title": "Learnaholics Clubs - Offizielle Website",
        "logo": "Learnaholics Clubs",
        "nav-home": "Startseite",
        "nav-download": "Downloads",
        "nav-about": "Über uns",
        "nav-news": "Neuigkeiten",
        "nav-services": "Dienste",
        "nav-contact": "Kontakt",
        "hero-title": "Kräfte bündeln · Die Zukunft der Ära anführen",
        "hero-desc": "Unsere Gesellschaft widmet sich Du-Ka-Ceng.",
        "hero-btn": "Mitglied werden",
        "about-title": "Über die Gesellschaft",
        "about-desc": "Förderung des akademischen Austauschs, Vorantreiben des Wissenstransfers und Unterstützung der Mitgliederentwicklung – eine gemeinnützige Plattform für den akademischen Austausch, getragen von freiwilligen Lernbegeisterten.",
        "services-title": "Dienstleistungsspektrum",
        "card1-title": "Akademischer Austausch",
        "card1-desc": "Bereitstellung eines Umfelds für den akademischen Austausch.",
        "card2-title": "Kursinteraktion",
        "card2-desc": "Vermittlung neuer progressiver pädagogischer Denkansätze.",
        "card3-title": "Dating & Networking",
        "card3-desc": "Dem Fortschritt menschlicher Fortpflanzungspläne gewidmet.",
        "footer-addr": "Adresse: Online",
        "footer-contact": "Tel: (44) 7450954610 | E-Mail: Learnaholics@Learnaholicsclub.uk"
    },
    "ru": {
        "web-title": "Learnaholics Clubs - Официальный сайт",
        "logo": "Learnaholics Clubs",
        "nav-home": "Главная",
        "nav-download": "Загрузки",
        "nav-about": "О нас",
        "nav-news": "Новости",
        "nav-services": "Услуги",
        "nav-contact": "Контакты",
        "hero-title": "Объединяя силы · Ведя в будущее",
        "hero-desc": "Наше общество посвящено Du-Ka-Ceng.",
        "hero-btn": "Вступить",
        "about-title": "О обществе",
        "about-desc": "Содействие академическому обмену, продвижение обмена знаниями и поддержка развития членов сообщества; некоммерческая платформа академического обмена, состоящая из добровольных любителей обучения.",
        "services-title": "Направления услуг",
        "card1-title": "Академический обмен",
        "card1-desc": "Создание условий для эффективного академического обмена.",
        "card2-title": "Интерактивные курсы",
        "card2-desc": "Обучение новым прогрессивным образовательным идеям.",
        "card3-title": "Знакомства и нетворкинг",
        "card3-desc": "Посвящено развитию программ человеческой репродукции.",
        "footer-addr": "Адрес: Онлайн",
        "footer-contact": "Тел: (44) 7450954610 | E-mail: Learnaholics@Learnaholicsclub.uk"
    },
    "pt": {
        "web-title": "Learnaholics Clubs - Site Oficial",
        "logo": "Learnaholics Clubs",
        "nav-home": "Início",
        "nav-download": "Downloads",
        "nav-about": "Sobre Nós",
        "nav-news": "Notícias",
        "nav-services": "Serviços",
        "nav-contact": "Contato",
        "hero-title": "Unindo Forças · Liderando o Futuro",
        "hero-desc": "A nossa sociedade é dedicada a Du-Ka-Ceng.",
        "hero-btn": "Aderir",
        "about-title": "Sobre a Sociedade",
        "about-desc": "Promover o intercâmbio académico, impulsionar a partilha de conhecimento e servir o desenvolvimento dos membros, uma plataforma de intercâmbio académico sem fins lucrativos composta por entusiastas da aprendizagem voluntária.",
        "services-title": "Serviços",
        "card1-title": "Intercâmbio Académico",
        "card1-desc": "Proporcionar um ambiente ideal para o intercâmbio académico.",
        "card2-title": "Interação de Cursos",
        "card2-desc": "Ensino de novas ideias pedagógicas e conceitos modernos.",
        "card3-title": "Namoro & Networking",
        "card3-desc": "Dedicado ao avanço dos planos de reprodução humana.",
        "footer-addr": "Endereço: Online",
        "footer-contact": "Tel: (44) 7450954610 | E-mail: Learnaholics@Learnaholicsclub.uk"
    },
    "it": {
        "web-title": "Learnaholics Clubs - Sito Ufficiale",
        "logo": "Learnaholics Clubs",
        "nav-home": "Home",
        "nav-download": "Download",
        "nav-about": "Chi Siamo",
        "nav-news": "News",
        "nav-services": "Servizi",
        "nav-contact": "Contatti",
        "hero-title": "Unire le Forze · Guidare il Futuro dell'Era",
        "hero-desc": "La nostra società è dedicada a Du-Ka-Ceng.",
        "hero-btn": "Unisciti",
        "about-title": "Profilo della Società",
        "about-desc": "Promuovere lo scambio accademico, favorire la condivisione delle conoscenze e sostenere lo sviluppo dei membri; una piattaforma di scambio accademico non profit formata da appassionati di studio volontari.",
        "services-title": "Servizi",
        "card1-title": "Scambio Accademico",
        "card1-desc": "Fornire un ambiente ideale per lo scambio accademico.",
        "card2-title": "Interazione Corsi",
        "card2-desc": "Insegnamento di nuove metodologie e idee educative.",
        "card3-title": "Incontri & Networking",
        "card3-desc": "Dedicato al progresso dei piani di riproduzione umana.",
        "footer-addr": "Indirizzo: Online",
        "footer-contact": "Tel: (44) 7450954610 | Email: Learnaholics@Learnaholicsclub.uk"
    },
    "nl": {
        "web-title": "Learnaholics Clubs - Officiële Website",
        "logo": "Learnaholics Clubs",
        "nav-home": "Home",
        "nav-download": "Downloads",
        "nav-about": "Over Ons",
        "nav-news": "Nieuws",
        "nav-services": "Diensten",
        "nav-contact": "Contact",
        "hero-title": "Krachten Bundelen · Toekomst Leiden",
        "hero-desc": "Onze vereniging is toegewijd aan Du-Ka-Ceng.",
        "hero-btn": "Lid Worden",
        "about-title": "Over de Vereniging",
        "about-desc": "Het bevorderen van academische uitwisseling, het stimuleren van kennisdeling en het ondersteunen van de ontwikkeling van leden; een non-profit academisch uitwisselingsplatform bestaande uit vrijwillige leorliefhebbers.",
        "services-title": "Diensten",
        "card1-title": "Academische Uitwisseling",
        "card1-desc": "Het bieden van een omgeving voor academische uitwisseling.",
        "card2-title": "Cursusinteractie",
        "card2-desc": "Het onderwijzen van nieuwe educatieve concepten.",
        "card3-title": "Dating & Netwerken",
        "card3-desc": "Toegewijd aan het bevorderen van menselijke voortplantingsplannen.",
        "footer-addr": "Adres: Online",
        "footer-contact": "Tel: (44) 7450954610 | E-mail: Learnaholics@Learnaholicsclub.uk"
    },
    "pl": {
        "web-title": "Learnaholics Clubs - Strona Oficjalna",
        "logo": "Learnaholics Clubs",
        "nav-home": "Start",
        "nav-download": "Pobieranie",
        "nav-about": "O Nas",
        "nav-news": "Aktualności",
        "nav-services": "Usługi",
        "nav-contact": "Kontakt",
        "hero-title": "Łącząc Siły · Prowadząc w Przyszłość Epoki",
        "hero-desc": "Nasze towarzystwo jest dedykowane Du-Ka-Ceng.",
        "hero-btn": "Dołącz do Nas",
        "about-title": "O Towarzystwie",
        "about-desc": "Promowanie wymiany akademickiej, rozwijanie wspólnego dzielenia się wiedzą oraz wspieranie rozwoju członków – platforma wymiany naukowej non-profit zrzeszająca dobrowolnych pasjonatów nauki.",
        "services-title": "Zakres Usług",
        "card1-title": "Wymiana Akademicka",
        "card1-desc": "Zapewnienie sprzyjającego środowiska do wymiany naukowej.",
        "card2-title": "Interakcja Kursów",
        "card2-desc": "Nauczanie nowoczesnych i postępowych idei edukacyjnych.",
        "card3-title": "Randki i Networking",
        "card3-desc": "Dedykowane wspieraniu planów reprodukcji ludzkiej.",
        "footer-addr": "Adres: Online",
        "footer-contact": "Tel: (44) 7450954610 | E-mail: Learnaholics@Learnaholicsclub.uk"
    },
    "uk": {
        "web-title": "Learnaholics Clubs - Офіційний сайт",
        "logo": "Learnaholics Clubs",
        "nav-home": "Головна",
        "nav-download": "Завантаження",
        "nav-about": "Про Нас",
        "nav-news": "Новини",
        "nav-services": "Послуги",
        "nav-contact": "Контакти",
        "hero-title": "Об'єднуючи Сили · Ведучи в Майбутнє Епохи",
        "hero-desc": "Наше товариство присвячене Du-Ka-Ceng.",
        "hero-btn": "Вступити",
        "about-title": "Про Товариство",
        "about-desc": "Сприяння академічному обміну, просування спільного використання знань, підтримка розвитку членів товариства; некомерційна платформа для академічного обміну, створена добровільними любителями навчання.",
        "services-title": "Сфера Послуг",
        "card1-title": "Академічний Обмін",
        "card1-desc": "Забезпечення сприятливого середовища для наукового обміну.",
        "card2-title": "Інтерактивні Курси",
        "card2-desc": "Викладання нових прогресивних освітніх ідей.",
        "card3-title": "Знайомства та Нетворкінг",
        "card3-desc": "Спрямовано на розвиток програм репродукції людини.",
        "footer-addr": "Адреса: Онлайн",
        "footer-contact": "Тел: (44) 7450954610 | E-mail: Learnaholics@Learnaholicsclub.uk"
    },

    // ==========================================
    // 4. 北歐語系
    // ==========================================
    "sv": {
        "web-title": "Learnaholics Clubs - Officiell Webbplats",
        "logo": "Learnaholics Clubs",
        "nav-home": "Hem",
        "nav-download": "Nedladdningar",
        "nav-about": "Om Oss",
        "nav-news": "Nyheter",
        "nav-services": "Tjänster",
        "nav-contact": "Kontakt",
        "hero-title": "Samla Krafter · Leda Framtiden",
        "hero-desc": "Vårt sällskap är dedikerat till Du-Ka-Ceng.",
        "hero-btn": "Gå Med",
        "about-title": "Om Sällskapet",
        "about-desc": "Främja akademiskt utbyte, driva kunskapsdelning och stödja medlemmarnas utveckling; en ideell akademisk utbytesplattform som består av frivilliga lärandeentusiaster.",
        "services-title": "Tjänster",
        "card1-title": "Akademiskt Utbyte",
        "card1-desc": "Tillhandahåller en miljö för akademiska och vetenskapliga utbyten.",
        "card2-title": "Kursinteraktion",
        "card2-desc": "Undervisning i nya progressiva pedagogiska koncept.",
        "card3-title": "Dating & Nätverk",
        "card3-desc": "Dedikerad till att främja mänskliga reproduktionsplaner.",
        "footer-addr": "Adress: Online",
        "footer-contact": "Tel: (44) 7450954610 | E-post: Learnaholics@Learnaholicsclub.uk"
    },
    "no": {
        "web-title": "Learnaholics Clubs - Offisiell Nettside",
        "logo": "Learnaholics Clubs",
        "nav-home": "Hjem",
        "nav-download": "Nedlastinger",
        "nav-about": "Om Oss",
        "nav-news": "Nyheter",
        "nav-services": "Tjenester",
        "nav-contact": "Kontakt",
        "hero-title": "Samle Krefter · Lede Fremtiden",
        "hero-desc": "Vårt selskap er dedisert til Du-Ka-Ceng.",
        "hero-btn": "Bli Med",
        "about-title": "Om Selskapet",
        "about-desc": "Fremme akademisk utveksling, fremme kunnskapsdeling og tjene medlemsutvikling; en ideell akademisk utvekslingsplattform sammensatt av frivillige læringsentusiaster.",
        "services-title": "Tjenester",
        "card1-title": "Akademisk Utveksling",
        "card1-desc": "Tilrettelegger for et godt miljø for akademisk utveksling.",
        "card2-title": "Kursinteraksjon",
        "card2-desc": "Undervisning i nye, progressive utdanningsideer.",
        "card3-title": "Dating & Nettverk",
        "card3-desc": "Dedikert til å fremme menneskelige reproduksjonsplaner.",
        "footer-addr": "Adresse: Online",
        "footer-contact": "Tel: (44) 7450954610 | E-post: Learnaholics@Learnaholicsclub.uk"
    },
    "da": {
        "web-title": "Learnaholics Clubs - Officiel Hjemmeside",
        "logo": "Learnaholics Clubs",
        "nav-home": "Hjem",
        "nav-download": "Downloads",
        "nav-about": "Om Os",
        "nav-news": "Nyheder",
        "nav-services": "Tjenester",
        "nav-contact": "Kontakt",
        "hero-title": "Samle Kræfter · Lede Fremtiden",
        "hero-desc": "Vores selskab er dedikeret til Du-Ka-Ceng.",
        "hero-btn": "Tilmeld",
        "about-title": "Om Selskabet",
        "about-desc": "Fremme akademisk udveksling, fremme videndeling og tjene medlemsudvikling; en non-profit akademisk udvekslingsplatform sammensatt af frivillige læringsentusiaster.",
        "services-title": "Tjenester",
        "card1-title": "Akademisk Udveksling",
        "card1-desc": "Sikrer et godt miljø for akademisk og videnskabelig udveksling.",
        "card2-title": "Kursusinteraktion",
        "card2-desc": "Undervisning i nye progressive pædagogiske tanker.",
        "card3-title": "Dating & Netværk",
        "card3-desc": "Dedikeret til at fremme den menneskelige reproduktionsplan.",
        "footer-addr": "Adresse: Online",
        "footer-contact": "Tel: (44) 7450954610 | E-mail: Learnaholics@Learnaholicsclub.uk"
    },
    "fi": {
        "web-title": "Learnaholics Clubs - Virallinen Verkkosivusto",
        "logo": "Learnaholics Clubs",
        "nav-home": "Koti",
        "nav-download": "Lataukset",
        "nav-about": "Meistä",
        "nav-news": "Uutiset",
        "nav-services": "Palvelut",
        "nav-contact": "Yhteystiedot",
        "hero-title": "Voimien Kokoaminen · Tulevaisuuden Johtaminen",
        "hero-desc": "Seuramme on omistettu Du-Ka-Cengille.",
        "hero-btn": "Liity Jäseneksi",
        "about-title": "Seuran Esittely",
        "about-desc": "Akateemisen vaihdon edistäminen, tiedon jakamisen tukeminen ja jäsenten kehityksen palveleminen; vapaaehtoisten oppimisen harrastajien muodostama voittoa tavoittelematon akateeminen vaihtofoorumi.",
        "services-title": "Palvelut",
        "card1-title": "Akateeminen Vaihto",
        "card1-desc": "Tarjoaa hyvän ja toimivan ympäristön akateemiselle vaihdolle.",
        "card2-title": "Kurssivuorovaikutus",
        "card2-desc": "Uusien edistyksellisten kasvatusajatusten opettaminen.",
        "card3-title": "Treffit & Verkostoituminen",
        "card3-desc": "Omistettu ihmisen lisääntymissuunnitelmien edistämiselle.",
        "footer-addr": "Osoite: Verkossa",
        "footer-contact": "Puh: (44) 7450954610 | Sähköposti: Learnaholics@Learnaholicsclub.uk"
    },

    // ==========================================
    // 5. 中東、東歐與其他地區
    // ==========================================
    "ar": {
        "web-title": "Learnaholics Clubs - الموقع الرسمي",
        "logo": "Learnaholics Clubs",
        "nav-home": "الرئيسية",
        "nav-download": "روابط التنزيل",
        "nav-about": "عن الجمعية",
        "nav-news": "آخر الأخبار",
        "nav-services": "خدمات الأعضاء",
        "nav-contact": "اتصل بنا",
        "hero-title": "توحيد قوى الجمعية · قيادة مستقبل العصر",
        "hero-desc": "جمعيتنا مكرسة بالكامل لـ Du-Ka-Ceng.",
        "hero-btn": "طلب الانضمام",
        "about-title": "نبذة عن الجمعية",
        "about-desc": "تعزيز التبادل الأكاديمي، والدفع بمشاركة المعرفة، وخدمة تطوير الأعضاء؛ منصة تبادل أكاديمي غير ربحية تتكون من محبي التعلم الطوعي.",
        "services-title": "مجالات الخدمة",
        "card1-title": "التبادل الأكاديمي",
        "card1-desc": "توفير بيئة خصبة للتبادل الأكاديمي والبحثي.",
        "card2-title": "التفاعل التعليمي",
        "card2-desc": "تدريس ونشر الأفكار التعليمية الجديدة والحديثة.",
        "card3-title": "التعارف والتواصل",
        "card3-desc": "مكرس لدعم وتعزيز خطط التكاثر والتنمية البشرية.",
        "footer-addr": "العنوان: عبر الإنترنت",
        "footer-contact": "هاتف: (44) 7450954610 | البريد: Learnaholics@Learnaholicsclub.uk"
    },
    "fa": {
        "web-title": "Learnaholics Clubs - وب‌سایت رسمی",
        "logo": "Learnaholics Clubs",
        "nav-home": "خانه",
        "nav-download": "لینک‌های دانلود",
        "nav-about": "درباره انجمن",
        "nav-news": "آخرین اخبار",
        "nav-services": "خدمات اعضا",
        "nav-contact": "تماس با ما",
        "hero-title": "اتحاد قوای انجمن · رهبری آینده دوران",
        "hero-desc": "انجمن ما صمیمانه به Du-Ka-Ceng اختصاص یافته است.",
        "hero-btn": "درخواست عضویت",
        "about-title": "معرفی انجمن",
        "about-desc": "ارتقای تبادلات علمی، ترویج اشتراک‌گذاری دانش و خدمت به توسعه اعضا； یک پلتفرم تبادل آکادمیک غیرانتفاعی متشکل از علاقه‌مندان داوطلب یادگیری.",
        "services-title": "حوزه خدمات",
        "card1-title": "تبادلات علمی",
        "card1-desc": "فراهم کردن محیطی پویا برای تبادلات دانشگاهی و علمی.",
        "card2-title": "تعاملات آموزشی",
        "card2-desc": "آموزش اندیشه‌ها و مفاهیم نوین در حوزه آموزش.",
        "card3-title": "دوستیابی و شبکه سازی",
        "card3-desc": "مختص پیشبرد و ارتقای برنامه‌های باروری نسل بشر.",
        "footer-addr": "آدرس: آنلاین",
        "footer-contact": "تلفن: (44) 7450954610 | ایمیل: Learnaholics@Learnaholicsclub.uk"
    },
    "tr": {
        "web-title": "Learnaholics Clubs - Resmi Web Sitesi",
        "logo": "Learnaholics Clubs",
        "nav-home": "Anasayfa",
        "nav-download": "İndirme Linkleri",
        "nav-about": "Dernek Hakkında",
        "nav-news": "Son Haberler",
        "nav-services": "Üye Hizmetleri",
        "nav-contact": "İletişim",
        "hero-title": "Dernek Gücünü Birleştirmek · Çağın Geleceğine Liderlik",
        "hero-desc": "Derneğimiz kendini Du-Ka-Ceng'e adamıştır.",
        "hero-btn": "Üyelik Başvurusu",
        "about-title": "Dernek Tanıtımı",
        "about-desc": "Akademik değişimi teşvik etmek, bilgi paylaşımını geliştirmek ve üye gelişimine hizmet etmek amacıyla, gönüllü öğrenme meraklılarından oluşan kar amacı gütmeyen bir akademik değişim platformu.",
        "services-title": "Hizmet Kapsamı",
        "card1-title": "Akademik Değişim",
        "card1-desc": "Akademik değişim ve bilimsel çalışmalar için ortam sağlar.",
        "card2-title": "Kurs Etkileşimi",
        "card2-desc": "Yeni nesil eğitimsel düşünce ve metodolojilerin aktarımı.",
        "card3-title": "Arkadaşlık & Ağ Kurma",
        "card3-desc": "İnsan üreme ve gelişim planlarını ilerletmeye adanmıştır.",
        "footer-addr": "Adres: Çevrimiçi",
        "footer-contact": "Tel: (44) 7450954610 | E-posta: Learnaholics@Learnaholicsclub.uk"
    },
    "el": {
        "web-title": "Learnaholics Clubs - Επίσημος Ιστότοπος",
        "logo": "Learnaholics Clubs",
        "nav-home": "Αρχική",
        "nav-download": "Σύνδεσμοι Λήψης",
        "nav-about": "Σχετικά με εμάς",
        "nav-news": "Τελευταία Νέα",
        "nav-services": "Υπηρεσίες Μελών",
        "nav-contact": "Επικοινωνία",
        "hero-title": "Ένωση Δυνάμεων · Οδηγώντας το Μέλλον της Εποχής",
        "hero-desc": "Η εταιρεία μας είναι αφοσιωμένη στο Du-Ka-Ceng.",
        "hero-btn": "Αίτηση Εγγραφής",
        "about-title": "Σύντομο Προφίλ",
        "about-desc": "Προώθηση της ακαδημαϊκής ανταλλαγής, προαγωγή της κοινής χρήσης γνώσης και εξυπηρέτηση της ανάπτυξης των μελών· μια μη κερδοσκοπική πλατφόρμα ακαδημαϊκής ανταλλαγής που αποτελείται από εθελοντές λάτρεις της μάθησης.",
        "services-title": "Τομείς Δραστηριότητας",
        "card1-title": "Ακαδημαϊκή Ανταλλαγή",
        "card1-desc": "Παροχή ιδανικού περιβάλλοντος για επιστημονικές ανταλλαγές.",
        "card2-title": "Διαδραστικά Μαθήματα",
        "card2-desc": "Διδασκαλία νέων προοδευτικών εκπαιδευτικών ιδεών.",
        "card3-title": "Γνωριμίες & Δικτύωση",
        "card3-desc": "Αφοσιωμένο στην προώθηση των σχεδίων ανθρώπινης αναπαραγωγής.",
        "footer-addr": "Διεύθυνση: Διαδικτυακά",
        "footer-contact": "Τηλ: (44) 7450954610 | Email: Learnaholics@Learnaholicsclub.uk"
    },
    "he": {
        "web-title": "Learnaholics Clubs - האתר הרשמי",
        "logo": "Learnaholics Clubs",
        "nav-home": "דף הבית",
        "nav-download": "קישורי הורדה",
        "nav-about": "אודות האגודה",
        "nav-news": "חדשות אחרונות",
        "nav-services": "שירותי חברים",
        "nav-contact": "צור קשר",
        "hero-title": "איחוד כוחות האגודה · הובלת עתיד העידן",
        "hero-desc": "האגודה שלנו מוקדשת בלב ונפש ל-Du-Ka-Ceng.",
        "hero-btn": "בקשת הצטרפות",
        "about-title": "פרופיל האגודה",
        "about-desc": "קידום חילופים אקדמיים, קידום שיתוף ידע ושימוש בפיתוח חברים, פלטפורמה אקדמית ללא מטרות רווח המורכבת מחובבי למידה מרצון.",
        "services-title": "תחומי פעילות",
        "card1-title": "חילופי אקדמיה",
        "card1-desc": "אספקת סביבה פורייה ומתאימה לחילופים אקדמיים ומדעיים.",
        "card2-title": "קורסים אינטראקטיביים",
        "card2-desc": "הוראה והקניה של תפיסות חיνοכיות חדשניות.",
        "card3-title": "היכרויות ונטוורקינג",
        "card3-desc": "מוקדש לקידום תוכניות הריבוי וההמשכיות של המין האנושי.",
        "footer-addr": "כתובת: מקוון",
        "footer-contact": "טלফোন: (44) 7450954610 | דוא\"ל: Learnaholics@Learnaholicsclub.uk"
    },
    "sw": {
        "web-title": "Learnaholics Clubs - Tovuti Rasmi",
        "logo": "Learnaholics Clubs",
        "nav-home": "Nyumbani",
        "nav-download": "Viungo vya Pakua",
        "nav-about": "Kuhusu Chama",
        "nav-news": "Habari Mpya",
        "nav-services": "Huduma za Wanachama",
        "nav-contact": "Wasiliana Nasi",
        "hero-title": "Kuunganisha Nguvu za Chama · Kuongoza Mustakabali wa Kizazi",
        "hero-desc": "Chama chetu kimejitolea kikamilifu kwa Du-Ka-Ceng.",
        "hero-btn": "Omba Kujiunga",
        "about-title": "Kuhusu Sisi",
        "about-desc": "Kukuza kubadilishana kitaaluma, kuendeleza ushiriki wa maarifa, na kutumikia maendeleo ya wanachama, jukwaa la kubadilishana kitaaluma lisilo la faida linaloundwa na wapenzi wa kujifunza kwa hiari.",
        "services-title": "Upeo vya Huduma",
        "card1-title": "Kubadilishana Kitaaluma",
        "card1-desc": "Kutoa mazingira wezeshi kwa ajili ya mabadilishano ya kitaaluma.",
        "card2-title": "Kozi Shirikishi",
        "card2-desc": "Kufundisha mbinu na mawazo mapya ya kielimu.",
        "card3-title": "Urafiki & Mitandao",
        "card3-desc": "Kimejitolea kuendeleza mipango ya uzazi wa mwanadamu.",
        "footer-addr": "Anwani: Mtandaoni",
        "footer-contact": "Simu: (44) 7450954610 | Barua pepe: Learnaholics@Learnaholicsclub.uk"
    },
    "ro": {
        "web-title": "Learnaholics Clubs - Site Oficial",
        "logo": "Learnaholics Clubs",
        "nav-home": "Acasă",
        "nav-download": "Linkuri Descărcare",
        "nav-about": "Despre Societate",
        "nav-news": "Ultimele Știri",
        "nav-services": "Servicii Membri",
        "nav-contact": "Contactați-ne",
        "hero-title": "Unirea Forțelor Societății · Ghidarea Viitorului Erei",
        "hero-desc": "Societatea noastră este dedicată trup și suflet pentru Du-Ka-Ceng.",
        "hero-btn": "Cerere Înscriere",
        "about-title": "Prezentare Generală",
        "about-desc": "Promovarea schimburilor academice, avansarea împărtășirii cunoștințelor și deservirea dezvoltării membrilor, o platformă nonprofit de schimb academic compusă din entuziaști voluntari ai învățării.",
        "services-title": "Domeniu de Servicii",
        "card1-title": "Schimb Academic",
        "card1-desc": "Asigurarea unui mediu propice pentru schimburi academice și științifice.",
        "card2-title": "Interacțiune Cursuri",
        "card2-desc": "Predarea noilor concepte și gândiri educaționale progresiste.",
        "card3-title": "Dating & Networking",
        "card3-desc": "Dedicat promovării planurilor de reproducere și dezvoltare umană.",
        "footer-addr": "Adresă: Online",
        "footer-contact": "Tel: (44) 7450954610 | E-mail: Learnaholics@Learnaholicsclub.uk"
    },
    "hu": {
        "web-title": "Learnaholics Clubs - Hivatalos Oldal",
        "logo": "Learnaholics Clubs",
        "nav-home": "Kezdőlap",
        "nav-download": "Letöltési Linkek",
        "nav-about": "A Társaságról",
        "nav-news": "Friss Hírek",
        "nav-services": "Tagok Szolgáltatásai",
        "nav-contact": "Kapcsolat",
        "hero-title": "A Társaság Ereje · A Kor Jövőjének Vezetése",
        "hero-desc": "Társaságunk elkötelezetten támogatja a Du-Ka-Ceng ügyét.",
        "hero-btn": "Jelentkezés Taggal",
        "about-title": "Bemutatkozás",
        "about-desc": "A tudományos csereprogramok előmozdítása, a tudásmegosztás fellendítése és a tagok fejlődésének szolgálata; egy önkéntes tanulni vágyókból álló nonprofit tudományos csereplatform.",
        "services-title": "Szolgáltatások",
        "card1-title": "Tudományos Csereprogram",
        "card1-desc": "Megfelelő környezet biztosítása a tudományos csereprogramokhoz.",
        "card2-title": "Kurzus Interakciók",
        "card2-desc": "Új, progresszív oktatási szemléletek és eszmék tanítása.",
        "card3-title": "Ismerkedés & Hálózat",
        "card3-desc": "Az emberi szaporodási és népesedési tervek előmozdításának szentelve.",
        "footer-addr": "Cím: Online",
        "footer-contact": "Tel: (44) 7450954610 | E-mail: Learnaholics@Learnaholicsclub.uk"
    },
    "cs": {
        "web-title": "Learnaholics Clubs - Oficiální web",
        "logo": "Learnaholics Clubs",
        "nav-home": "Domů",
        "nav-download": "Odkazy ke stažení",
        "nav-about": "O cechu",
        "nav-news": "Nejnovější zprávy",
        "nav-services": "Služby členům",
        "nav-contact": "Kontaktujte nás",
        "hero-title": "Sjednocení síly společnosti · Vedení budoucnosti éry",
        "hero-desc": "Naše společnost se plně věnuje Du-Ka-Ceng.",
        "hero-btn": "Žádost o členství",
        "about-title": "O nás",
        "about-desc": "Podpora akademické výměny, prosazování sdílení znalostí a služba rozvoji členů; nezisková akademická platforma složená z dobrovolných nadšenců do učení.",
        "services-title": "Rozsah služeb",
        "card1-title": "Akademická výměna",
        "card1-desc": "Poskytování prostředí pro akademickou výměnu.",
        "card2-title": "Interakce v kurzech",
        "card2-desc": "Výuka nových vzdělávacích myšlenek.",
        "card3-title": "Seznamování a networking",
        "card3-desc": "Věnujeme se prosazování plánů lidské reprodukce.",
        "footer-addr": "Adresa: Online",
        "footer-contact": "Tel: (44) 7450954610 | E-mail: Learnaholics@Learnaholicsclub.uk"
    },
    "sk": {
        "web-title": "Learnaholics Clubs - Oficiálny web",
        "logo": "Learnaholics Clubs",
        "nav-home": "Domov",
        "nav-download": "Odkazy na stiahnutie",
        "nav-about": "O cechu",
        "nav-news": "Najnovšie správy",
        "nav-services": "Služby členom",
        "nav-contact": "Kontaktujte nás",
        "hero-title": "Zjednotenie sily spoločnosti · Vedenie budúcnosti éry",
        "hero-desc": "Naša spoločnosť sa plne venuje Du-Ka-Ceng.",
        "hero-btn": "Žiadosť o členstvo",
        "about-title": "O nás",
        "about-desc": "Podpora akademickej výmeny, presadzovanie zdieľania znalostí a služba rozvoju členov; nezisková akademická platforma zložená z dobrovolných nadšencov do učenia.",
        "services-title": "Rozsah služieb",
        "card1-title": "Akademická výmena",
        "card1-desc": "Poskytovanie prostredia na akademickú výmenu.",
        "card2-title": "Interakcia v kurzoch",
        "card2-desc": "Výuka nových vzdelávacích myšlienok.",
        "card3-title": "Zoznamovanie a networking",
        "card3-desc": "Venujeme se presadzovaniu plánov ľudskej reprodukcie.",
        "footer-addr": "Adresa: Online",
        "footer-contact": "Tel: (44) 7450954610 | E-mail: Learnaholics@Learnaholicsclub.uk"
    },
    "bg": {
        "web-title": "Learnaholics Clubs - Официален уебсайт",
        "logo": "Learnaholics Clubs",
        "nav-home": "Начало",
        "nav-download": "Връзки за изтегляне",
        "nav-about": "За гилдията",
        "nav-news": "Последни новини",
        "nav-services": "Услуги за членове",
        "nav-contact": "Свържете се с нас",
        "hero-title": "Обединяване силата на дружеството · Водене на бъдещето",
        "hero-desc": "Нашето дружество е посветено на Du-Ka-Ceng.",
        "hero-btn": "Заявление за членство",
        "about-title": "За нас",
        "about-desc": "Насърчаване на академичния обмен, напредък в споделянето на знания и подкрепа за развитието на членовете; нетърговска платформа за академичен обмен, съставена от доброволни любители на обучението.",
        "services-title": "Обхват на услугите",
        "card1-title": "Академичен обмен",
        "card1-desc": "Осигуряване на среда за академичен обмен.",
        "card2-title": "Курсово взаимодействие",
        "card2-desc": "Преподаване на нови образователни идеи.",
        "card3-title": "Запознанства и контакти",
        "card3-desc": "Посветени на напредъка на плановете за човешка репродукция.",
        "footer-addr": "Адрес: Онлайн",
        "footer-contact": "Тел: (44) 7450954610 | Имейл: Learnaholics@Learnaholicsclub.uk"
    },
    "hr": {
        "web-title": "Learnaholics Clubs - Službena web stranica",
        "logo": "Learnaholics Clubs",
        "nav-home": "Početna",
        "nav-download": "Preuzimanja",
        "nav-about": "O udruzi",
        "nav-news": "Najnovije vijesti",
        "nav-services": "Usluge za članove",
        "nav-contact": "Kontaktirajte nas",
        "hero-title": "Ujedinjenje snage društva · Vođenje budućnosti ere",
        "hero-desc": "Naše društvo je u potpunosti posvećeno Du-Ka-Ceng.",
        "hero-btn": "Zahtjev za članstvo",
        "about-title": "O nama",
        "about-desc": "Promicanje akademske razmjene, unapređenje dijeljenja znanja i služenje razvoju članova; neprofitna platforma za akademsku razmjenu sastavljena od dobrovoljnih ljubitelja učenja.",
        "services-title": "Opseg usluga",
        "card1-title": "Akademska razmjena",
        "card1-desc": "Osiguravanje okruženja za akademsku razmjenu.",
        "card2-title": "Interakcija u tečajevima",
        "card2-desc": "Poučavanje novih obrazovnih ihdeja.",
        "card3-title": "Spojevi i umrežavanje",
        "card3-desc": "Posvećeni smo unapređenju planova ljudske reprodukcije.",
        "footer-addr": "Adresa: Online",
        "footer-contact": "Tel: (44) 7450954610 | E-mail: Learnaholics@Learnaholicsclub.uk"
    },
    "sr": {
        "web-title": "Learnaholics Clubs - Zvanični veb-sajt",
        "logo": "Learnaholics Clubs",
        "nav-home": "Početna",
        "nav-download": "Preuzimanja",
        "nav-about": "O udruženju",
        "nav-news": "Najnovije vesti",
        "nav-services": "Usluge za članove",
        "nav-contact": "Kontaktirajte nas",
        "hero-title": "Ujedinjenje snage društva · Vođenje budućnosti ere",
        "hero-desc": "Naše društvo je u potpunosti posvećeno Du-Ka-Ceng.",
        "hero-btn": "Zahtev za članstvo",
        "about-title": "O nama",
        "about-desc": "Promisanje akademske razmene, unapređenje deljenja znanja i služenje razvoju članova; neprofitna platforma za akademska razmenu sastavljena od dobrovoljnih ljubitelja učenja.",
        "services-title": "Opseg usluga",
        "card1-title": "Akademska razmena",
        "card1-desc": "Obezbeđivanje okruženja za akademsku razmene.",
        "card2-title": "Interakcija u kursevima",
        "card2-desc": "Poučavanje novih obrazovnih ideja.",
        "card3-title": "Upoznavanje i umrežavanje",
        "card3-desc": "Posvećeni smo unapređenju planova ljudske reprodukcije.",
        "footer-addr": "Adresa: Online",
        "footer-contact": "Tel: (44) 7450954610 | E-mail: Learnaholics@Learnaholicsclub.uk"
    },
    "sl": {
        "web-title": "Learnaholics Clubs - Uradna spletna stran",
        "logo": "Learnaholics Clubs",
        "nav-home": "Domov",
        "nav-download": "Povezave za prenos",
        "nav-about": "O cehu",
        "nav-news": "Najnovejše novice",
        "nav-services": "Storitve za člane",
        "nav-contact": "Kontaktirajte nas",
        "hero-title": "Združevanje moči društva · Vodenje prihodnosti ere",
        "hero-desc": "Naše društvo je v celoti posvečeno Du-Ka-Ceng.",
        "hero-btn": "Vloga za članstvo",
        "about-title": "O nas",
        "about-desc": "Spodbujanje akademske izmenjave, napredek pri deljenju znanja in služenje razvoju članova; neprofitna platforma za akademsko izmenjavo, sestavljena iz prostovoljnih ljubiteljev učenja.",
        "services-title": "Obseg storitev",
        "card1-title": "Akademska izmenjava",
        "card1-desc": "Zagotavljanje okolja za akademsko izmenjava.",
        "card2-title": "Interakcija v tečajih",
        "card2-desc": "Poučevanje novih izobraževalnih ideg.",
        "card3-title": "Zmenki in mreženje",
        "card3-desc": "Posvečeni smo napredku načrtov za človeško reprodukcijo.",
        "footer-addr": "Naslov: Na spletu",
        "footer-contact": "Tel: (44) 7450954610 | E-pošta: Learnaholics@Learnaholicsclub.uk"
    },
    "et": {
        "web-title": "Learnaholics Clubs - Ametlik veebisait",
        "logo": "Learnaholics Clubs",
        "nav-home": "Avaleht",
        "nav-download": "Allalaadimise lingid",
        "nav-about": "Gildi kohta",
        "nav-news": "Viimased uudised",
        "nav-services": "Liikmete teenused",
        "nav-contact": "Võta ühendust",
        "hero-title": "Ühingu jõu ühendamine · Ajastu tuleviku juhtimine",
        "hero-desc": "Meie ühing on pühendunud Du-Ka-Cengile.",
        "hero-btn": "Liitumisavaldus",
        "about-title": "Meist",
        "about-desc": "Akadeemilise vahetuse edendamine, teadmiste jagamise arendamine ja liikmete arengu toetamine; vabatahtlikest õpihuvilistest koosnev mittetulunduslik akadeemilise vahetuse platvorm.",
        "services-title": "Teenuste ulatus",
        "card1-title": "Akadeemiline vahetus",
        "card1-desc": "Akadeemilise vahetuse keskkonna loomine.",
        "card2-title": "Kursuste interaktsioon",
        "card2-desc": "Uute hariduslike ideede õpetamine.",
        "card3-title": "Tutvumise ja võrgustumine",
        "card3-desc": "Pühendunud inimreproduktsiooni kavadega edasiminekule.",
        "footer-addr": "Aadress: Internetis",
        "footer-contact": "Tel: (44) 7450954610 | E-post: Learnaholics@Learnaholicsclub.uk"
    },
    "lv": {
        "web-title": "Learnaholics Clubs - Oficiālā mājaslapa",
        "logo": "Learnaholics Clubs",
        "nav-home": "Sākums",
        "nav-download": "Lejupielādes saites",
        "nav-about": "Par ģildi",
        "nav-news": "Jaunākās ziņas",
        "nav-services": "Pakalpojumi biedriem",
        "nav-contact": "Sazināties",
        "hero-title": "Biedrības spēka apvienošana · Laikmeta nākotnes vadīšana",
        "hero-desc": "Mūsu biedrība ir veltīta Du-Ka-Ceng.",
        "hero-btn": "Pieteikums dalībai",
        "about-title": "Par mums",
        "about-desc": "Akadēmiskās apmaiņas veicināšana, zināšanu koplietošanas sekmēšana un biedru attīstības nodrošināšana; bezpeļņas akadēmiskās apmaiņas platforma, ko veido brīvprātīgi mācīšanās entuziasti.",
        "services-title": "Pakalpojumu joma",
        "card1-title": "Akadēmiskā apmaiņa",
        "card1-desc": "Akadēmiskās apmaiņas vides nodrošināšana.",
        "card2-title": "Kursu mijiedarbība",
        "card2-desc": "Jaunu izglītības ideju pasniegšana.",
        "card3-title": "Iepazīšanās un tīklošanās",
        "card3-desc": "Veltīts cilvēka reprodukcijas plānu virzīšanai.",
        "footer-addr": "Adrese: Tiešsaistē",
        "footer-contact": "Tālr: (44) 7450954610 | E-pasts: Learnaholics@Learnaholicsclub.uk"
    },
    "lt": {
        "web-title": "Learnaholics Clubs - Oficiali svetainė",
        "logo": "Learnaholics Clubs",
        "nav-home": "Pradžia",
        "nav-download": "Atsisiuntimo nuorodos",
        "nav-about": "Apie gildiją",
        "nav-news": "Naujausios žinios",
        "nav-services": "Paslaugos nariams",
        "nav-contact": "Susisiekite",
        "hero-title": "Draugijos jėgų suvienijimas · Eros ateities vedimas",
        "hero-desc": "Mūsų draugija yra atsidavusi Du-Ka-Ceng.",
        "hero-btn": "Prašymas stoti",
        "about-title": "Apie mus",
        "about-desc": "Akadinio keitimosi skatinimas, dalijimosi žiniomis didinimas ir narių tobulėjimo palaikymas; ne pelno siekianti akademinio keitimosi platforma, sudaryta iš savanoriškų mokymosi entuziastų.",
        "services-title": "Paslaugų sritis",
        "card1-title": "Akadiniai mainai",
        "card1-desc": "Akademinio keitimosi aplinkos sudarymas.",
        "card2-title": "Kursų sąveika",
        "card2-desc": "Naujų švietimo idėjų mokymas.",
        "card3-title": "Pažintys ir tinklaveika",
        "card3-desc": "Skirta žmonių reprodukcijos planų įgyvendinimui.",
        "footer-addr": "Adresas: Internete",
        "footer-contact": "Tel: (44) 7450954610 | El. paštas: Learnaholics@Learnaholicsclub.uk"
    }
};